global_frame: odom
rolling_window: true

obstacles:
  publish_voxel_map: true
  observation_sources: point_cloud_sensor

  point_cloud_sensor: {
    sensor_frame: zed_frame_optical,
    data_type: PointCloud2,
    topic: "/zed/point_cloud/cloud_registered",
    expected_update_rate: 0.5,
    marking: true,
    clearing: true,
    min_obstacle_height: -99999.0,
    max_obstacle_height: 99999.0}
plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
